version: '3'

services:
  db:
    image: postgres:latest
    container_name: video-nairoki-db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'video-nairoki'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_EXTENSIONS: uuid-ossp
volumes:
  db-store:
